FROM centos

USER root

RUN yum -y update && yum -y install epel-release
RUN yum -y update && yum -y install vim python python-pip git

COPY . /work
WORKDIR /work
RUN pip install -r automated/utils/requirements.txt

CMD . ./automated/bin/setenv.sh && test-runner -p plans/linux-example.yaml && bash

