FROM fedora:44

RUN dnf -y install vim python3 python3-pip git

COPY . /work
WORKDIR /work
RUN pip3 install -r automated/utils/requirements.txt

CMD . ./automated/bin/setenv.sh && test-runner -p plans/linux-test-plan-example.yaml && bash
