version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    - pip install -r requirements-docs.txt
    - python generate_test_docs.py
    - zensical build -c
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - cp -r site/* $READTHEDOCS_OUTPUT/html/
