metadata:
    name: apk-automation
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "Automated benchmarking with APKs on Android."
    maintainer:
        - milosz.wasilewski@linaro.org
        - chase.qi@linaro.org
    os:
        - android
    devices:
        - juno
        - hi6220-hikey
        - x15
    scope:
        - performance

params:
    SKIP_INSTALL: "false"
    # Timeout for wait_boot_completed in seconds.
    BOOT_TIMEOUT: "300"
    # Specify adb device SN if more then one device connected.
    ANDROID_SERIAL: ""
    TEST_NAME: "linpack"
    LOOPS: "5"
    APK_DIR: "./apks"
    # Specify url and token for file uploading.
    URL: "https://archive.validation.linaro.org/artifacts/team/qa/"
    TOKEN: "4373c97b474497dbd12373689d7d492e"

run:
    steps:
        - cd ./automated/android/apk-automation
        - ./apk-automation.sh -S "${SKIP_INSTALL}" -t "${BOOT_TIMEOUT}" -s "${ANDROID_SERIAL}" -n "${TEST_NAME}" -l "${LOOPS}" -d "${APK_DIR}"
        # Upload test output to artifactorial.
        - tar caf "output-${TEST_NAME}.tar.xz" "./output"
        - ../../utils/upload-to-artifactorial.sh -a "output-${TEST_NAME}.tar.xz" -u "${URL}" -t "${TOKEN}"
        # Send test result to LAVA.
        - ../../utils/send-to-lava.sh ./output/result.txt
