java.sql.Array.ArrayTest
java.sql.Blob.BlobTest
java.sql.Clob.ClobTest
java.sql.Connection.TestJdbc
java.sql.DatabaseMetaData.TestJdbc
java.sql.Date.DateTest
java.sql.DriverManager.DriverManagerTest
java.sql.Time.TimeTest
java.sql.Timestamp.TimestampTest
java.sql.Types.TestJdbc10
java.sql.Types.TestJdbc20
