#!/bin/bash

# JTREG LAVA test harness.
#
# Copyright (C) 2013, Linaro Limited.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# Author: Andrew McDermott <andrew.mcdermott@linaro.org>
#

if [ $# -lt 2 ]; then
    echo "usage: $0: <test-dir> <test>" >&2
    exit 1
fi

if [ -z "$PRODUCT_HOME" ]; then
    echo "error: PRODUCT_HOME not set!" >&2
    exit 1
fi

if [ -z "$JT_HOME" ]; then
    echo "error: JT_HOME not set!" >&2
    exit 1
fi

if [ -z "$JTREG" ]; then
    JTREG=$JT_HOME/linux/bin/jtreg-lava
fi

set -x

uniq_pathname() {
    local name=$1
    name=${name#$to/}
    name=${name////-}
    echo $to/$name
}

test_dir=$1
test_to_run=$2

t=/tmp/jtreg/$test_to_run.$$
rm -rf $t
mkdir -p $t
to=$t/testoutput

# Accommodate differences between jdk tests and hotspot tests.
#
# The hotspot tests need to be invoked with TESTDIRS set and they also
# put the output one directory deeper and the output content (and
# location) is different to the jdk tests.
#
if [ -n "$TESTDIRS" ]; then
    lava-test-case $test_to_run \
        --shell \
        make -C $test_dir PRODUCT_HOME=$PRODUCT_HOME JTREG=$JTREG JT_HOME=$JT_HOME ALT_OUTPUTDIR=$t TESTDIRS=$TESTDIRS

    exit_code=$?
    to=`ls -1d $t/*/testoutput`
    zip --quiet -d $to/ARCHIVE_BUNDLE.zip 'JTwork/classes/*'
    mv $to/ARCHIVE_BUNDLE.zip $to/${test_to_run}-ARCHIVE_BUNDLE.zip
    lava-test-case-attach $test_to_run $to/${test_to_run}-ARCHIVE_BUNDLE.zip
    shopt -s nullglob
    for i in $to/JTwork/scratch/hs*.log; do
        lava-test-case-attach $test_to_run $i
    done
else
    lava-test-case $test_to_run \
        --shell \
        make -C $test_dir PRODUCT_HOME=$PRODUCT_HOME JTREG=$JTREG JT_HOME=$JT_HOME ALT_OUTPUTDIR=$t $test_to_run

    exit_code=$?

    shopt -s nullglob

    for i in $to/${test_to_run}*/*.txt; do
        name=$(uniq_pathname $i)
        cp $i $name
        if [ -s $name ]; then
            lava-test-case-attach $test_to_run $name
        fi
    done

    for i in $to/${test_to_run}*/JTwork/scratch/hs*.log; do
        lava-test-case-attach $test_to_run $i
    done

    for i in $to/${test_to_run}*/ARCHIVE_BUNDLE.zip; do
        zip --quiet -d $i 'JTwork/classes/*'
        name=$(uniq_pathname $i)
        cp $i $name
        if [ -s $name ]; then
            lava-test-case-attach $test_to_run $name
        fi
    done

    for i in $to/${test_to_run}*/Stats.txt; do
        cat $i
    done
fi

rm -rf $t

exit $exit_code
