#!/usr/bin/env python3
"""
conf_to_yaml.py
Advantech BSP QA – .conf → LAVA YAML params converter

Reads a bash-style .conf file that defines CFGA_* associative arrays and
generates per-module YAML params override files suitable for inclusion in
LAVA test definitions.

Usage:
    python3 conf_to_yaml.py <board.conf> [--out-dir <dir>] [--module <name>]

Example:
    python3 conf_to_yaml.py ../conf/rom2620-ed91_modbsp.conf --out-dir /tmp/yaml

Copyright (c) 2024 Advantech Co., Ltd. All rights reserved
"""

import argparse
import os
import re
import sys
from collections import defaultdict
from typing import Dict, List, Optional

# ─── Pattern helpers ──────────────────────────────────────────────────────────

# Match lines like:
#   [key·sub]=value
#   [key:sub]=value
#   [key]=value
#   [key·sub]="quoted value"
ENTRY_RE = re.compile(r"""\[([^\]]+)\]\s*=\s*(?:"([^"]*)"|((?:[^\s)\]]*)))""")


def parse_conf(path: str) -> Dict[str, Dict[str, str]]:
    """
    Parse a .conf file and return a dict of {array_name: {key: value}}.
    """
    arrays: Dict[str, Dict[str, str]] = defaultdict(dict)
    current_array: Optional[str] = None

    with open(path, encoding="utf-8") as fh:
        for raw_line in fh:
            line = raw_line.strip()

            # Detect array declaration: declare -A CFGA_XXX=(
            m = re.match(r"declare\s+-A[gG]?\s+(CFGA_\w+)\s*=\s*\(", line)
            if m:
                current_array = m.group(1)
                # May have entries on the same line
                rest = line[m.end():]
                for em in ENTRY_RE.finditer(rest):
                    key, v_quoted, v_bare = em.groups()
                    arrays[current_array][key] = (v_quoted if v_quoted is not None else v_bare)
                continue

            # Closing paren ends the array block
            if current_array and line.startswith(")"):
                current_array = None
                continue

            if current_array:
                for em in ENTRY_RE.finditer(line):
                    key, v_quoted, v_bare = em.groups()
                    arrays[current_array][key] = (v_quoted if v_quoted is not None else v_bare)

    return dict(arrays)


# ─── Key-naming helpers ───────────────────────────────────────────────────────

F3 = "·"   # U+00B7 MIDDLE DOT

def split_key(raw_key: str):
    """Return (instance, subkey) from a raw array key like 'eth0·dev'."""
    if F3 in raw_key:
        parts = raw_key.split(F3, 1)
        return parts[0], parts[1]
    if ":" in raw_key:
        parts = raw_key.split(":", 1)
        return parts[0], parts[1]
    return None, raw_key


def instances_of(data: Dict[str, str]) -> List[str]:
    """Return sorted unique instance names from an array (eth0, eth1, …)."""
    seen = []
    for k in data:
        inst, _ = split_key(k)
        if inst and inst not in seen:
            seen.append(inst)
    return seen


def to_yaml_scalar(value: str) -> str:
    """Quote a YAML scalar value if needed."""
    if not value:
        return '""'
    # Quote if the string contains characters that may confuse YAML parsers
    if re.search(r'[:#\[\]{}|>&*!,?@`%]', value) or value[0] in '"\'':
        # Use double-quotes; escape internal double-quotes
        return '"' + value.replace('"', '\\"') + '"'
    return value


def write_yaml(path: str, params: Dict[str, str]) -> None:
    """Write a LAVA params YAML fragment to path."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("# Auto-generated by conf_to_yaml.py – do not edit by hand\n")
        fh.write("params:\n")
        for k, v in params.items():
            fh.write(f"  {k}: {to_yaml_scalar(v)}\n")


# ─── Per-module converters ────────────────────────────────────────────────────

def conv_context(sw: Dict, cpu: Dict) -> Dict[str, str]:
    p: Dict[str, str] = {}
    p["DISTRO_ID"] = sw.get("distro:id", "")
    p["DISTRO_VER"] = sw.get("distro:ver", "")
    p["KERNEL_MIN_VER"] = sw.get("kernel:min-ver") or sw.get("kernel-min-ver", "")
    p["CPU_MODEL"] = cpu.get("model", "")
    p["BIOS_DATE"] = sw.get("bios:date", "")
    return p


def conv_thermal(thermal: Dict) -> Dict[str, str]:
    insts = instances_of(thermal)
    p: Dict[str, str] = {"THERMAL_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        pfx = f"TZ{idx}"
        p[f"{pfx}_DEV"]  = thermal.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_MIN"]  = thermal.get(f"{inst}{F3}min", "10")
        p[f"{pfx}_MAX"]  = thermal.get(f"{inst}{F3}max", "95")
    return p


def conv_i2c(i2c: Dict) -> Dict[str, str]:
    insts = instances_of(i2c)
    p: Dict[str, str] = {"I2C_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        pfx = f"I2C{idx}"
        p[f"{pfx}_DEV"]        = i2c.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_CONTROLLER"] = i2c.get(f"{inst}{F3}controller", "")
        p[f"{pfx}_REFERENCE"]  = i2c.get(f"{inst}{F3}reference", "")
    return p


def conv_pwm(pwm: Dict) -> Dict[str, str]:
    insts = instances_of(pwm)
    p: Dict[str, str] = {"PWM_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        pfx = f"PWM{idx}"
        p[f"{pfx}_DEV"]       = pwm.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_BUS"]       = pwm.get(f"{inst}{F3}bus", "")
        p[f"{pfx}_BUS_ID"]    = pwm.get(f"{inst}{F3}bus_id", "")
        p[f"{pfx}_REFERENCE"] = pwm.get(f"{inst}{F3}reference", "")
    p["PWM_BACKLIGHT_DEV"] = pwm.get("backlight-dev", "")
    return p


def conv_spi(spi: Dict) -> Dict[str, str]:
    insts = instances_of(spi)
    p: Dict[str, str] = {"SPI_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        p[f"SPI{idx}_DEV"] = spi.get(f"{inst}{F3}dev", "")
    return p


def conv_npu(npu: Dict) -> Dict[str, str]:
    insts = instances_of(npu)
    p: Dict[str, str] = {"NPU_COUNT": str(max(len(insts), 1))}
    for idx, inst in enumerate(insts):
        pfx = f"NPU{idx}"
        p[f"{pfx}_DEV"]              = npu.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_BUS"]              = npu.get(f"{inst}{F3}bus", "")
        p[f"{pfx}_BUS_ID"]           = npu.get(f"{inst}{F3}bus_id", "")
        p[f"{pfx}_BUS_DEVICE_TYPE"]  = npu.get(f"{inst}{F3}bus_device_type", "")
        p[f"{pfx}_BUS_NODE_NAME"]    = npu.get(f"{inst}{F3}bus_node_name", "")
    return p


def conv_cpu(cpu: Dict) -> Dict[str, str]:
    p: Dict[str, str] = {
        "CPU_MODEL":             cpu.get("model", ""),
        "CPU_NPROC":             cpu.get("nproc", ""),
        "CPU_CSTATES":           cpu.get("cstates", ""),
        "CPU_SCALING_MIN":       cpu.get("scaling-min", "0"),
        "CPU_SCALING_MAX":       cpu.get("scaling-max", "0"),
        "CPU_SCALING_GOVERNORS": cpu.get("scaling-governors", ""),
        "CPU_SUSPENSION_STATES": cpu.get("suspension", ""),
    }
    return p


def conv_ram(ram: Dict) -> Dict[str, str]:
    insts = instances_of(ram)
    p: Dict[str, str] = {
        "RAM_SLOT_COUNT": str(len(insts)),
        "RAM_MIN_AVAIL":  ram.get("min-avail", "800"),
    }
    for idx, inst in enumerate(insts):
        p[f"RAM_SLOT{idx}_SIZE"]  = ram.get(f"{inst}{F3}size", "")
        p[f"RAM_SLOT{idx}_SPEED"] = ram.get(f"{inst}{F3}speed", "")
    return p


def conv_disk(disk: Dict) -> Dict[str, str]:
    insts = instances_of(disk)
    insts = [i for i in insts if i not in ("rootfs",)]
    p: Dict[str, str] = {
        "DISK_COUNT":        str(len(insts)),
        "DISK_ROOTFS_MOUNT": disk.get("rootfs:mount", ""),
    }
    for idx, inst in enumerate(insts):
        pfx = f"DISK{idx}"
        p[f"{pfx}_DEV"]     = disk.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_TYPE"]    = disk.get(f"{inst}{F3}type", "")
        p[f"{pfx}_SECTORS"] = disk.get(f"{inst}{F3}sectors", "0")
        p[f"{pfx}_MIN_RS"]  = disk.get(f"{inst}{F3}min-rs", "0")
        p[f"{pfx}_MIN_WS"]  = disk.get(f"{inst}{F3}min-ws", "0")
    return p


def conv_eth(eth: Dict) -> Dict[str, str]:
    insts = instances_of(eth)
    p: Dict[str, str] = {
        "ETH_COUNT":         str(len(insts)),
        "IPERF3_SERVER_IP":  "",
        "IPERF3_DURATION":   "5",
    }
    for idx, inst in enumerate(insts):
        pfx = f"ETH{idx}"
        p[f"{pfx}_DEV"]          = eth.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_BUS"]          = eth.get(f"{inst}{F3}bus", "")
        p[f"{pfx}_BUS_ID"]       = eth.get(f"{inst}{F3}bus_id", "")
        p[f"{pfx}_LINK"]         = eth.get(f"{inst}{F3}link", "")
        p[f"{pfx}_WOL_FEATURED"] = eth.get(f"{inst}{F3}wol:featured") or \
                                    eth.get(f"{inst}{F3}wol-featured", "")
        p[f"{pfx}_WOL_WAKEUP"]   = eth.get(f"{inst}{F3}wol:enabled") or \
                                    eth.get(f"{inst}{F3}wol-wakeup", "")
        p[f"{pfx}_MIN_TX_SPEED"] = eth.get(f"{inst}{F3}min-tx-speed", "0")
        p[f"{pfx}_MIN_RX_SPEED"] = eth.get(f"{inst}{F3}min-rx-speed", "0")
    return p


def conv_uart(uart: Dict) -> Dict[str, str]:
    insts = instances_of(uart)
    p: Dict[str, str] = {"UART_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        pfx = f"UART{idx}"
        lt = uart.get(f"{inst}{F3}loopback-test", "skip")
        p[f"{pfx}_DEV"]             = uart.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_BUS"]             = uart.get(f"{inst}{F3}bus", "")
        p[f"{pfx}_BUS_ID"]          = uart.get(f"{inst}{F3}bus_id", "")
        p[f"{pfx}_HWFC"]            = uart.get(f"{inst}{F3}hwfc", "0")
        p[f"{pfx}_DEBUG_CONSOLE"]   = uart.get(f"{inst}{F3}debug-console", "0")
        p[f"{pfx}_LOOPBACK_TEST"]   = lt
        p[f"{pfx}_REFERENCE"]       = uart.get(f"{inst}{F3}reference", "")
    return p


def conv_can(can: Dict) -> Dict[str, str]:
    insts = [i for i in instances_of(can) if i != "ext-loopback-tests"]
    ext = can.get("ext-loopback-tests", "")
    p: Dict[str, str] = {
        "CAN_COUNT":         str(len(insts)),
        "CAN_EXT_LOOPBACK":  ext,
    }
    for idx, inst in enumerate(insts):
        pfx = f"CAN{idx}"
        p[f"{pfx}_DEV"]               = can.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_BUS"]               = can.get(f"{inst}{F3}bus", "")
        p[f"{pfx}_BUS_ID"]            = can.get(f"{inst}{F3}bus_id", "")
        p[f"{pfx}_CLOCK"]             = can.get(f"{inst}{F3}clock", "")
        p[f"{pfx}_LOOPBACK_SPEEDS"]   = can.get(f"{inst}{F3}loopback-test-speeds", "125000 500000")
    return p


def conv_gpio(gpio: Dict) -> Dict[str, str]:
    insts = instances_of(gpio)
    p: Dict[str, str] = {
        "GPIO_COUNT": str(len(insts)),
        "GPIO_PINS":  "",
    }
    for idx, inst in enumerate(insts):
        pfx = f"GPIO{idx}"
        p[f"{pfx}_DEV"]        = gpio.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_CHIP"]       = gpio.get(f"{inst}{F3}chip", "")
        p[f"{pfx}_CONTROLLER"] = gpio.get(f"{inst}{F3}controller", "")
        p[f"{pfx}_NLINES"]     = gpio.get(f"{inst}{F3}nlines", "0")
    return p


def conv_usb(usb: Dict, cfgc_usb: Dict) -> Dict[str, str]:
    dev_insts = [k for k in usb if F3 in k and "port" in k.split(F3, 1)[1]]
    # deduplicate to instance names
    insts = []
    for k in dev_insts:
        inst = k.split(F3, 1)[0]
        if inst not in insts:
            insts.append(inst)
    p: Dict[str, str] = {
        "USB_DEV_COUNT":   str(len(insts)),
        "USB_OTG_ENABLED": "1" if usb.get("otg", "n") in ("y", "1") else "0",
        "USB_OTG_CONF":    cfgc_usb.get("otg-conf", ""),
    }
    for idx, inst in enumerate(insts):
        pfx = f"USB_DEV{idx}"
        p[f"{pfx}_PORT"]   = usb.get(f"{inst}{F3}port", "")
        p[f"{pfx}_DRIVER"] = usb.get(f"{inst}{F3}driver", "")
        p[f"{pfx}_SPEED"]  = usb.get(f"{inst}{F3}speed", "")
    return p


def conv_rtc(rtc: Dict) -> Dict[str, str]:
    insts = instances_of(rtc)
    p: Dict[str, str] = {"RTC_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        pfx = f"RTC{idx}"
        p[f"{pfx}_DEV"]    = rtc.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_WAKEUP"] = rtc.get(f"{inst}{F3}wakeup", "")
    # First RTC is also used for suspend
    if insts:
        inst0 = insts[0]
        p["RTC_SUSPEND_DEV"]           = rtc.get(f"{inst0}{F3}dev", "/dev/rtc0")
        p["RTC_SUSPEND_SLEEP_STATE"]   = "mem"
        p["RTC_SUSPEND_WAKE_SLEEP_S"]  = rtc.get(f"{inst0}{F3}wake-sleep-time-s", "5")
    return p


def conv_watchdog(wdog: Dict) -> Dict[str, str]:
    insts = instances_of(wdog)
    p: Dict[str, str] = {"WATCHDOG_COUNT": str(len(insts))}
    for idx, inst in enumerate(insts):
        p[f"WATCHDOG{idx}_DEV"] = wdog.get(f"{inst}{F3}dev", "")
    return p


def conv_tpm(tpm: Dict) -> Dict[str, str]:
    insts = instances_of(tpm)
    p: Dict[str, str] = {"TPM_COUNT": str(max(len(insts), 1))}
    for idx, inst in enumerate(insts):
        pfx = f"TPM{idx}"
        caps = tpm.get(f"{inst}{F3}tpm2:caps", "")
        ver  = "2" if caps else "1"
        p[f"{pfx}_DEV"]    = tpm.get(f"{inst}{F3}dev", "")
        p[f"{pfx}_VERSION"] = ver
        p[f"{pfx}_MANUF1"] = tpm.get(f"{inst}{F3}manuf1", "")
        p[f"{pfx}_MANUF2"] = tpm.get(f"{inst}{F3}manuf2", "")
        p[f"{pfx}_CAPS"]   = caps
    return p


def conv_optee(optee: Dict) -> Dict[str, str]:
    return {"OPTEE_DEV": optee.get("dev", "/dev/tee0")}


def conv_audio(aplayback: Dict, acapture: Dict) -> Dict[str, str]:
    pb_insts = instances_of(aplayback)
    cap_insts = instances_of(acapture)
    p: Dict[str, str] = {
        "AUDIO_PLAYBACK_COUNT": str(len(pb_insts)),
        "AUDIO_CAPTURE_COUNT":  str(len(cap_insts)),
    }
    for idx, inst in enumerate(pb_insts):
        pfx = f"AUDIO_PB{idx}"
        p[f"{pfx}_CARD"]       = aplayback.get(f"{inst}{F3}card", "")
        p[f"{pfx}_CONTROLLER"] = aplayback.get(f"{inst}{F3}controller", "")
        p[f"{pfx}_DEV_ID"]     = aplayback.get(f"{inst}{F3}dev-id", "")
        p[f"{pfx}_CODEC"]      = aplayback.get(f"{inst}{F3}codec", "")
    for idx, inst in enumerate(cap_insts):
        pfx = f"AUDIO_CAP{idx}"
        p[f"{pfx}_CARD"]       = acapture.get(f"{inst}{F3}card", "")
        p[f"{pfx}_CONTROLLER"] = acapture.get(f"{inst}{F3}controller", "")
        p[f"{pfx}_DEV_ID"]     = acapture.get(f"{inst}{F3}dev-id", "")
        p[f"{pfx}_CODEC"]      = acapture.get(f"{inst}{F3}codec", "")
    return p


def conv_gpu(gpu: Dict) -> Dict[str, str]:
    insts = [i for i in instances_of(gpu)
             if i not in ("desktop", "va")]
    p: Dict[str, str] = {
        "GPU_COUNT":   str(len(insts)),
        "GPU_WAYLAND": gpu.get("desktop:wayland", ""),
        "GPU_VA_CODECS": gpu.get("va:codecs", ""),
    }
    for idx, inst in enumerate(insts):
        pfx = f"GPU{idx}"
        p[f"{pfx}_DRI_KMS_DEV"]          = gpu.get(f"{inst}{F3}dri-kms-dev", "")
        p[f"{pfx}_BACKLIGHT_DEV"]         = gpu.get(f"{inst}{F3}backlight-dev", "")
        p[f"{pfx}_LVDS_MOD"]              = gpu.get(f"{inst}{F3}lvds-mod", "")
        p[f"{pfx}_LVDS_DEV"]              = gpu.get(f"{inst}{F3}lvds-dev", "")
        p[f"{pfx}_DRM_CONNECTOR"]         = gpu.get(f"{inst}{F3}drm-connector", "")
        p[f"{pfx}_DRM_CONNECTOR_ENCODER"] = gpu.get(f"{inst}{F3}drm-connector-encoder", "")
        p[f"{pfx}_RESOLUTION"]            = gpu.get(f"{inst}{F3}resolution", "")
        p[f"{pfx}_REFRESH_RATE"]          = gpu.get(f"{inst}{F3}refresh-rate", "")
    return p


# ─── Module registry ─────────────────────────────────────────────────────────

def generate_all(arrays: Dict[str, Dict[str, str]], out_dir: str) -> None:
    sw      = arrays.get("CFGA_SW", {})
    cpu     = arrays.get("CFGA_CPU", {})
    thermal = arrays.get("CFGA_THERMAL", {})
    i2c     = arrays.get("CFGA_I2C", {})
    pwm     = arrays.get("CFGA_PWM", {})
    spi     = arrays.get("CFGA_SPI", {})
    npu     = arrays.get("CFGA_NPU", {})
    ram     = arrays.get("CFGA_RAM", {})
    disk    = arrays.get("CFGA_DISK", {})
    eth     = arrays.get("CFGA_ETH", {})
    uart    = arrays.get("CFGA_UART", {})
    can     = arrays.get("CFGA_CAN", {})
    gpio    = arrays.get("CFGA_GPIO", {})
    usb     = arrays.get("CFGA_USB", {})
    cfgc_usb = arrays.get("CFGC_USB", {})
    rtc     = arrays.get("CFGA_RTC", {})
    wdog    = arrays.get("CFGA_WATCHDOG", {})
    tpm     = arrays.get("CFGA_TPM", {})
    optee   = arrays.get("CFGA_OPTEE", {})
    apb     = arrays.get("CFGA_APLAYBACK", {})
    acap    = arrays.get("CFGA_ACAPTURE", {})
    gpu     = arrays.get("CFGA_GPU", {})

    modules = {
        "context":  conv_context(sw, cpu),
        "thermal":  conv_thermal(thermal),
        "i2c":      conv_i2c(i2c),
        "pwm":      conv_pwm(pwm),
        "spi":      conv_spi(spi),
        "npu":      conv_npu(npu),
        "cpu":      conv_cpu(cpu),
        "ram":      conv_ram(ram),
        "disk":     conv_disk(disk),
        "eth":      conv_eth(eth),
        "uart":     conv_uart(uart),
        "can":      conv_can(can),
        "gpio":     conv_gpio(gpio),
        "usb":      conv_usb(usb, cfgc_usb),
        "rtc":      conv_rtc(rtc),
        "watchdog": conv_watchdog(wdog),
        "tpm":      conv_tpm(tpm),
        "optee":    conv_optee(optee),
        "audio":    conv_audio(apb, acap),
        "gpu":      conv_gpu(gpu),
    }

    for mod, params in modules.items():
        out_path = os.path.join(out_dir, mod, "params.yaml")
        write_yaml(out_path, params)
        print(f"  wrote {out_path}")


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Convert Advantech .conf to LAVA params YAML files"
    )
    ap.add_argument("conf", help="Path to the board .conf file")
    ap.add_argument(
        "--out-dir", "-o",
        default=os.path.join(os.path.dirname(__file__), "..", "lava"),
        help="Output root directory (default: ../lava relative to this script)"
    )
    ap.add_argument(
        "--module", "-m",
        help="Only generate YAML for this module (default: all modules)"
    )
    args = ap.parse_args()

    if not os.path.isfile(args.conf):
        print(f"ERROR: conf file not found: {args.conf}", file=sys.stderr)
        return 1

    print(f"Parsing: {args.conf}")
    arrays = parse_conf(args.conf)
    print(f"  found arrays: {', '.join(sorted(arrays))}")

    out_dir = os.path.realpath(args.out_dir)
    print(f"Output directory: {out_dir}")

    if args.module:
        # Single-module mode – generate all then advise; filtering by module
        # name is left as a future enhancement.
        generate_all(arrays, out_dir)
    else:
        generate_all(arrays, out_dir)

    return 0


if __name__ == "__main__":
    sys.exit(main())
