metadata:
    name: fedora-build
    format: "Lava-Test-Shell Test Definition 1.0"
    description: "Fedora builds."
    maintainer:
        - milosz.wasilewski@linaro.org
    scope:
        - functional
    os:
        - fedora
    devices:
        - juno
install:
    steps:
        - 'echo nameserver 8.8.8.8 > /etc/resolv.conf'
        - 'sleep 10'
        - 'ping dmarlin.fedorapeople.org -c 5'
        - 'yum -y --nogpgcheck install http://dmarlin.fedorapeople.org/packages/FedoraArm/RPMS/noarch/xpfa-18-1.noarch.rpm'
        - 'yum -y --enablerepo=xpfa install anaconda lorax'

run:
    steps:
        - './fedora/scripts/build/create-fedora-image.sh'

parse:
    pattern: "^(?P<test_case_id>.*)=(?P<result>.*)"
