metadata:
    name: fleet-wide-configuration
    format: "Manual Test Definition 1.0"
    description: "Set a factory wide configuration file"
    maintainer:
        - brendan.wood@foundires.io
    os:
        - ubuntu
        - openembedded
    scope:
        - functional
    devices:
        - 
    environment:
        - manual-test

run:
    steps:
        - "fioctl config set --reason <"">  -f <factory>  --create <filename>==<file-path>
        - ensure the device is currently registered to a factory
        - copy existing uuid
        - delete /var/sota/sql.db
        - Run lmp-device-register - u <existing UUID>
                       
    expected:
       - Device should not be able to register 
       - expected error - Unable to create device HTTP_409
       - message Conflict /ota/devices/? 
