name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pull docker image
      run: docker pull fsfe/reuse
    - name: REUSE Compliance Check
      run: docker run -v $(pwd):/test-definitions --workdir /test-definitions fsfe/reuse lint


